apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: beer-service
  name: beer-service
spec:
  ports:
  - name: 8084-8084
    port: 8084
    protocol: TCP
    targetPort: 8080
  selector:
    app: beer-service
  type: ClusterIP
status:
  loadBalancer: {}
